from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"


# Master rule for controlling workflow.
rule all:
	input:
		"index.html",

# Get dot rule graphs
rule dot_rules_graph:
    output:
        "dags/rulegraph.svg",
        "dags/rulegraph.png",
    conda:
        "envs/environment.yml"
    shell:
        """
        bash workflow/scripts/rules_dag.sh
        """

# Get project tree
rule project_tree:
    output:
        tree="results/project_tree.txt"
    conda:
        "envs/environment.yml"
    shell:
        """
        bash workflow/scripts/tree.sh
        """

# Get smk static report
rule static_snakemake_report:
    output:
        smkhtml="report.html",
        html2png="images/smkreport/screenshot.png"
    conda:
        "envs/environment.yml"
    shell:
        """
        bash workflow/scripts/smk_html_report.sh
        """

rule deploy_to_github_pages:
    input:
        script="workflow/scripts/render.R",
        rmd="index.Rmd",
        # rulegraph="dags/rulegraph.svg",
        tree="results/project_tree.txt",
        html2png="images/smkreport/screenshot.png",
    output:
        doc="index.html",
    conda:
        "envs/environment.yml"
    shell:
        """
        R -e "library(rmarkdown); render('{input.rmd}')"
        """

