# (PART) DIVERSITY ANALYSIS {-}

# QIIME2 Diversity Analysis
> As described [here](https://docs.qiime2.org/2019.7/tutorials/moving-pictures/#alpha-and-beta-diversity-analysis)


## Alpha diversity metrics
- Shannon’s diversity index (a quantitative measure of community richness)-
- Observed OTUs (a qualitative measure of community richness)
- Faith’s Phylogenetic Diversity (a qualitiative measure of community richness that incorporates phylogenetic relationships between the features)
- Evenness (or Pielou’s Evenness; a measure of community evenness)

## Beta diversity metrics 
- Jaccard distance (a qualitative measure of community dissimilarity)
- Bray-Curtis distance (a quantitative measure of community dissimilarity)
- unweighted UniFrac distance (a qualitative measure of community dissimilarity that incorporates phylogenetic relationships between the features)
- weighted UniFrac distance (a quantitative measure of community dissimilarity that incorporates phylogenetic relationships between the features)

## Expected output artifacts
- Saved FeatureTable[Frequency] to: qiime2_process/core-metrics/rarefied_table.qza
- Saved SampleData[AlphaDiversity] to: qiime2_process/core-metrics/faith_pd_vector.qza
- Saved SampleData[AlphaDiversity] to: qiime2_process/core-metrics/observed_features_vector.qza
- Saved SampleData[AlphaDiversity] to: qiime2_process/core-metrics/shannon_vector.qza
- Saved SampleData[AlphaDiversity] to: qiime2_process/core-metrics/evenness_vector.qza
- Saved DistanceMatrix to: qiime2_process/core-metrics/unweighted_unifrac_distance_matrix.qza
- Saved DistanceMatrix to: qiime2_process/core-metrics/weighted_unifrac_distance_matrix.qza
- Saved DistanceMatrix to: qiime2_process/core-metrics/jaccard_distance_matrix.qza
- Saved DistanceMatrix to: qiime2_process/core-metrics/bray_curtis_distance_matrix.qza
- Saved PCoAResults to: qiime2_process/core-metrics/unweighted_unifrac_pcoa_results.qza
- Saved PCoAResults to: qiime2_process/core-metrics/weighted_unifrac_pcoa_results.qza
- Saved PCoAResults to: qiime2_process/core-metrics/jaccard_pcoa_results.qza
- Saved PCoAResults to: qiime2_process/core-metrics/bray_curtis_pcoa_results.qza


## Expected output visualizations
- Saved Visualization to: qiime2_process/core-metrics/unweighted_unifrac_emperor.qzv
- Saved Visualization to: qiime2_process/core-metrics/weighted_unifrac_emperor.qzv
- Saved Visualization to: qiime2_process/core-metrics/jaccard_emperor.qzv
- Saved Visualization to: qiime2_process/core-metrics/bray_curtis_emperor.qzv


## Exploring beta diversity metric
- - Qiime2 uses `Emperor`interactive tool [@Emperor2013] for exploring beta diversity metrics

# (PART) DIFFERENTIAL ANALYSIS {-}
# Differential Abundance
QIIME2 uses ANCOM (Analysis of Composition) to identify differentially abundant taxa.




# (PART) QIIME2 OUTPUT ANALYSIS {-}

# Exploring QIIME 2 Output: Feature Table, Taxonomy, and Metadata

In this section, we'll explore key components, including the Feature Table, Taxonomy information, and associated metadata.

## Initial Data Exploration

Before jumping into the analysis, let's get acquainted with the primary outputs generated by QIIME 2:

1. **Feature Table:** This table represents the abundance of different features (microbial taxa or operational taxonomic units) across samples.

2. **Taxonomy Data:** Information on the taxonomic classification of each feature, helping us understand the microbial community composition.

3. **Metadata:** Additional information associated with each sample, providing context and experimental details.

## Starting the Analysis

1. **Load Data:** Begin by loading the Feature Table, Taxonomy, and metadata into your analysis environment.

```R
# Example R code for loading QIIME 2 data
feature_table <- read.table("path/to/feature_table.tsv", sep = "\t", header = TRUE, row.names = 1)
taxonomy_data <- read.table("path/to/taxonomy_data.tsv", sep = "\t", header = TRUE, row.names = 1)
metadata <- read.table("path/to/metadata.tsv", sep = "\t", header = TRUE, row.names = 1)
```