name: imap
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
  - anaconda
dependencies:
  - snakemake =7.19.1
  - snakemake-minimal =7.19.1
  - snakedeploy =0.8.6
  - python =3.11.0
  - pip -23.0.1
  - r-base =4.1.3
  - r-tidyverse =1.3.2 
  - r-bookdown =0.32
  - r-htmltools =0.5.4 
  - r-htmlwidgets =1.6.1
  - r-leaflet =2.1.1
  - r-leaflet.providers =1.9.0 
  - r-rmarkdown =2.20
  - r-schtools =0.4.0
  - graphviz =6.0.1
  - seaborn =0.12.2
  - numpy =1.24.2
  - matplotlib-base =3.7.1
  - pandas =1.5.3
  - html2text =2020.1.16
  - pandoc =2.19.2
  - tree 2.0.0

